import type { CelestialBodyView, NavigationTarget } from './types'

export interface RenderBody extends CelestialBodyView {
  renderRadius: number
  orbitRadius: number
  eccentricity: number
  inclination: number
  phase: number
  rotationHours: number
  hasClouds?: boolean
  hasRings?: boolean
  ringColor?: string
  palette: readonly [string, string, string, string]
}

export const STAR: CelestialBodyView = {
  id: 'asteria',
  name: 'Asteria',
  designation: 'AE-0001 · G2 V',
  kind: 'star',
  description: 'A stable yellow dwarf illuminating a deterministic, procedurally generated system.',
  radiusKm: 696_340,
  massEarths: 332_946,
  temperatureK: 5778,
  gravityG: 27.9,
  orbitalPeriodDays: 0,
  distanceAu: 0,
  atmosphere: 'Hydrogen · Helium plasma',
  discovered: 'Generator v0.1 · seed 7A51E2',
  color: '#ffd7a1',
  accent: '#ff8f5a',
}

export const RENDER_BODIES: readonly RenderBody[] = [
  {
    id: 'cinder',
    name: 'Cinder',
    designation: 'AE-0001 b · Ferrian',
    kind: 'desert',
    description: 'A scorched iron-rich world with long basaltic scarps and no persistent atmosphere.',
    radiusKm: 4210,
    massEarths: 0.52,
    temperatureK: 612,
    gravityG: 0.74,
    orbitalPeriodDays: 44.8,
    distanceAu: 0.32,
    atmosphere: 'Exosphere · Na · O₂',
    discovered: 'Procedural candidate · 7A51E2-b',
    color: '#a96a4d',
    accent: '#f2a16d',
    renderRadius: 0.72,
    orbitRadius: 14,
    eccentricity: 0.09,
    inclination: 0.08,
    phase: 0.7,
    rotationHours: 58.6,
    palette: ['#241b1b', '#6d3f32', '#a96a4d', '#e6ad7d'],
  },
  {
    id: 'pelagos',
    name: 'Pelagos',
    designation: 'AE-0001 c · Marine Terra',
    kind: 'oceanic',
    description: 'A temperate ocean world where volcanic archipelagos break through a cobalt global sea.',
    radiusKm: 6880,
    massEarths: 1.18,
    temperatureK: 289,
    gravityG: 1.02,
    orbitalPeriodDays: 221.7,
    distanceAu: 0.72,
    atmosphere: 'N₂ 76% · O₂ 21% · Ar',
    discovered: 'Procedural candidate · 7A51E2-c',
    color: '#1d8db9',
    accent: '#69d4df',
    renderRadius: 1.05,
    orbitRadius: 24,
    eccentricity: 0.035,
    inclination: 0.025,
    phase: 2.3,
    rotationHours: 27.4,
    hasClouds: true,
    palette: ['#052039', '#0d5b83', '#238fa1', '#7ca16f'],
  },
  {
    id: 'viridia',
    name: 'Viridia',
    designation: 'AE-0001 d · Temperate Terra',
    kind: 'terrestrial',
    description: 'A living super-Earth with shallow seas, broad cloud systems, and emerald continental shelves.',
    radiusKm: 8120,
    massEarths: 1.84,
    temperatureK: 302,
    gravityG: 1.13,
    orbitalPeriodDays: 387.2,
    distanceAu: 1.04,
    atmosphere: 'N₂ 72% · O₂ 24% · H₂O',
    discovered: 'Procedural candidate · 7A51E2-d',
    color: '#3d9d7d',
    accent: '#8bd5b6',
    renderRadius: 1.25,
    orbitRadius: 36,
    eccentricity: 0.021,
    inclination: 0.045,
    phase: 4.1,
    rotationHours: 21.2,
    hasClouds: true,
    palette: ['#061b2c', '#144b6b', '#2a7a66', '#b9c889'],
  },
  {
    id: 'orison',
    name: 'Orison',
    designation: 'AE-0001 e · Jovian',
    kind: 'gas-giant',
    description: 'A warm banded giant whose silicate ring plane shepherds a compact family of icy moons.',
    radiusKm: 61_920,
    massEarths: 184.2,
    temperatureK: 168,
    gravityG: 2.08,
    orbitalPeriodDays: 1862,
    distanceAu: 2.96,
    atmosphere: 'H₂ 89% · He 10% · CH₄',
    discovered: 'Procedural candidate · 7A51E2-e',
    color: '#c08d6e',
    accent: '#f3cda9',
    renderRadius: 2.65,
    orbitRadius: 57,
    eccentricity: 0.074,
    inclination: 0.09,
    phase: 5.5,
    rotationHours: 10.6,
    hasRings: true,
    ringColor: '#d6b89e',
    palette: ['#4f342c', '#94634d', '#d0a17b', '#f0d0ad'],
  },
  {
    id: 'nyx',
    name: 'Nyx',
    designation: 'AE-0001 f · Cryo-Neptune',
    kind: 'ice-giant',
    description: 'A distant methane-blue world turning beneath a high, electrically active haze layer.',
    radiusKm: 25_470,
    massEarths: 17.4,
    temperatureK: 71,
    gravityG: 1.14,
    orbitalPeriodDays: 8460,
    distanceAu: 8.14,
    atmosphere: 'H₂ 81% · He 18% · CH₄',
    discovered: 'Procedural candidate · 7A51E2-f',
    color: '#4d74b9',
    accent: '#8fb4ef',
    renderRadius: 1.8,
    orbitRadius: 83,
    eccentricity: 0.11,
    inclination: 0.13,
    phase: 1.4,
    rotationHours: 16.1,
    hasRings: true,
    ringColor: '#7a8da9',
    palette: ['#182950', '#315486', '#5d82bc', '#a4c5e8'],
  },
]

export const BODY_LOOKUP = new Map<string, CelestialBodyView>([
  [STAR.id, STAR],
  ...RENDER_BODIES.map((body) => [body.id, body] as const),
])

export const NAVIGATION_TARGETS: readonly NavigationTarget[] = [STAR, ...RENDER_BODIES].map(
  ({ id, name, kind, color }) => ({ id, name, kind, color }),
)
